### ISSUE TITLE
pyasn1 required version not found

### ISSUE THREAD

**Issue by mohamed-osama-aboelkheir** [theno/ctutlz#2]
It is giving the below error

```
verify-scts google.com --short
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 666, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 984, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 875, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (pyasn1 0.4.2 (/usr/local/lib/python3.6/site-packages), Requirement.parse('pyasn1<0.3.0,>=0.2.0'), {'ctutlz'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/verify-scts", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3147, in <module>
    @_call_aside
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3131, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3160, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 668, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 681, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 870, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pyasn1<0.3.0,>=0.2.0' distribution was not found and is required by ctutlz
```
It seems, the available version of pyasn1 is 0.4.2 which doesn't satisfy pyasn1<0.3.0,>=0.2.0.

https://pypi.python.org/pypi/pyasn1

**Comment by MrChapelle** [comment]
Hello,
I am trying tu use your library on MacOS.
After installing the library using : "pip install ctultz", I run the command "verify-scts google.com --short"
Then I obtain the following error : "Segmentation Fault: 11"

Can you tell me what I have to do to solve this issue ?

Thank you
